services:
  - type: web
    name: stock-project
    env: python
    buildCommand: |
      apt-get update && apt-get install -y libgomp1
      pip install -r build-requirements.txt && pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    branch: main
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
