services:
  - type: web
    name: stock-project
    env: python
    buildCommand: ./setup.sh
    startCommand: gunicorn app:app
    plan: free
    branch: main
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
