services:
  - type: web
    name: stock-project
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: bash -lc "gunicorn app:app --bind 0.0.0.0:$PORT"
    plan: free
    branch: main
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
